import Foundation
import os

/// UI language. English is the preferred (and base) language for new strings.
enum AppLanguage: String, CaseIterable, Codable, Identifiable {
    case system
    case english = "en"
    case russian = "ru"

    var id: String { rawValue }
}

/// Localization with on-the-fly language switching: strings come from the
/// selected language's .lproj bundle, bypassing the system setting.
enum L10n {
    private struct State {
        var bundle: Bundle
        var language: AppLanguage
    }

    /// The bundle is swapped on the main thread when the operator changes the
    /// language, and read from any thread that formats a message — the offload
    /// worker reports its progress from its own queue, and error toasts are
    /// built wherever the failure happened. As a plain `static var` that is a
    /// data race: ThreadSanitizer flags it, and a torn read of the reference
    /// is a crash on a machine whose timing differs from the one it ran on.
    private static let state = OSAllocatedUnfairLock(
        initialState: State(bundle: .module, language: .system))

    /// Copied out under the lock; the string lookup itself runs outside it.
    private static var bundle: Bundle {
        state.withLock { $0.bundle }
    }

    /// The bundle the current language's resources live in. Not everything
    /// localized is a string: the help page is a Markdown document per language,
    /// and it has to follow the in-app language switch like the strings do —
    /// reading it from `.module` would give whatever the SYSTEM language is.
    static var resources: Bundle { bundle }

    /// The language currently in force. Stored alongside the bundle because a
    /// Bundle cannot be mapped back to the choice that selected it, and callers
    /// that switch the language temporarily need to know what to switch back to.
    static var current: AppLanguage {
        state.withLock { $0.language }
    }

    static func apply(_ language: AppLanguage) {
        let selected: Bundle
        switch language {
        case .system:
            selected = .module
        case .english, .russian:
            if let path = Bundle.module.path(forResource: language.rawValue, ofType: "lproj"),
               let languageBundle = Bundle(path: path) {
                selected = languageBundle
            } else {
                selected = .module
            }
        }
        state.withLock { $0 = State(bundle: selected, language: language) }
    }

    static func string(_ key: String) -> String {
        bundle.localizedString(forKey: key, value: nil, table: nil)
    }

    /// The string for `key`, or nil when this build has none for it.
    ///
    /// `string(_:)` cannot answer that question: a missing key comes back AS
    /// the key, which is a plausible sentence to show and an implausible one to
    /// test against. The sentinel is what makes the answer exact — a key whose
    /// translation really is the key still resolves, because what comes back is
    /// the key and not the sentinel.
    ///
    /// This exists for exactly one caller: `BridgeUnavailable`, which has to
    /// tell "no words for this code yet" from "words that happen to look like
    /// the code" and fall back to the bridge's own English for the first.
    static func translation(_ key: String) -> String? {
        let sentinel = "\u{0}no-translation"
        let found = bundle.localizedString(forKey: key, value: sentinel,
                                           table: nil)
        return found == sentinel ? nil : found
    }

    static func string(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: string(key), arguments: arguments)
    }
}

extension AppLanguage {
    /// The locale documents generated by the app format their dates in — the
    /// shift report's header date follows the language its labels are in.
    /// `system` follows the machine, like the strings do.
    var documentLocale: Locale {
        switch self {
        case .system: return .current
        case .english: return Locale(identifier: "en_US")
        case .russian: return Locale(identifier: "ru_RU")
        }
    }
}

/// Short helper for views.
func L(_ key: String) -> String {
    L10n.string(key)
}

func L(_ key: String, _ arguments: CVarArg...) -> String {
    let format = L10n.string(key)
    guard LocalizedFormat.matches(format, arguments) else {
        // **A string that does not match its arguments must not be able to
        // take the app down.** `String(format:)` reads its argument list by
        // the conversions IN THE STRING, so a `%@` handed an Int builds a
        // pointer out of a small integer and dereferences it: EXC_BAD_ACCESS
        // at address 2, inside CoreFoundation, with nothing in the trace
        // naming the key. `LocalizationTests` holds the two languages to the
        // same conversions, which is the half that can be checked statically;
        // this is the other half — a CALL SITE that passes the wrong kind,
        // which no amount of reading the .strings files can see.
        //
        // The fallback is the format itself: visible nonsense on one line of
        // one panel, rather than a process that dies mid-take. In a debug
        // build it also trips an assertion, so the suite says which key.
        assertionFailure("L(\(key)) does not match its arguments: \(format)")
        return format
    }
    return String(format: format, arguments: arguments)
}

/// Whether a localized format and the values handed to it agree.
///
/// Deliberately conservative: it reports a mismatch only for the cases that
/// are certainly wrong — a different NUMBER of conversions, or a `%@` against
/// a number, or a numeric conversion against a string. Anything it cannot
/// judge it passes, because a false alarm here would replace a working
/// sentence with its own format string.
enum LocalizedFormat {
    static func matches(_ format: String, _ arguments: [CVarArg]) -> Bool {
        let conversions = self.conversions(in: format)
        // A positional format (`%1$@`) may legitimately use an argument twice
        // or leave a later one unused, so only a format asking for MORE than
        // it was given is certainly wrong there.
        if conversions.contains(where: \.isPositional) {
            return (conversions.compactMap(\.position).max() ?? 0)
                <= arguments.count
        }
        guard conversions.count == arguments.count else { return false }
        for (conversion, argument) in zip(conversions, arguments) {
            let isText = argument is String || argument is NSString
            if conversion.wantsObject != isText { return false }
        }
        return true
    }

    struct Conversion {
        /// `1` in `%1$@`, or nil for a plain conversion.
        var position: Int?
        /// `@` conversions take an object; every other one takes a scalar.
        var wantsObject: Bool
        var isPositional: Bool { position != nil }
    }

    /// The printf conversions in a format, in order, `%%` excluded.
    static func conversions(in format: String) -> [Conversion] {
        var found: [Conversion] = []
        var rest = Substring(format)
        while let percent = rest.firstIndex(of: "%") {
            rest = rest[rest.index(after: percent)...]
            guard let head = rest.first else { break }
            if head == "%" {
                rest = rest.dropFirst()
                continue
            }
            // `1$` is the position; then flags, width and precision; then the
            // conversion letter.
            var position: Int?
            let digits = rest.prefix(while: \.isNumber)
            if !digits.isEmpty, rest.dropFirst(digits.count).first == "$" {
                position = Int(digits)
                rest = rest.dropFirst(digits.count + 1)
            }
            rest = rest.drop { "+- #0123456789.'".contains($0) }
            rest = rest.drop { "hlLqjzt".contains($0) }
            guard let letter = rest.first else { break }
            rest = rest.dropFirst()
            found.append(Conversion(position: position, wantsObject: letter == "@"))
        }
        return found
    }
}
